sudo: false
language: node_js
node_js:
  - 6
  - 7
  - 8
  - 9
  - stable

before_install:
  - npm config set progress=false

before_script:
  - npm run lint

script: npm run cover

after_script:
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
